name: tmdb_api
description: 'Dart package for TMDB API client'
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  http: ^1.6.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.5
  json_serializable: ^6.11.4
  lints: ^6.0.0
